name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.MY_TOKEN }}
          PUBLISH_REPOSITORY: iamthecloverly/blog
          BRANCH: gh-pages
          PUBLISH_DIR: site
